version: '3'

services:
  nginx:
    build:
      context: ..
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
    links:
      - fpm
    volumes:
      - ../:/var/www/app
  fpm:
    container_name: infotech
    build: ./fpm
    depends_on:
      - db
    volumes:
      - ../:/var/www/app
  db:
    build:
      context: ..
      dockerfile: docker/mysql/Dockerfile
    restart: always
    ports:
      - "3306:3306"
#    command:
      #      - --init-file /docker-entrypoint-initdb.d/01.sql
#      - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - "./database:/var/lib/mysql/"

