CREATE DATABASE infotech CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE infotech_test CHARACTER SET utf8 COLLATE utf8_general_ci;

GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' WITH GRANT OPTION;